make cpuFactory paranoid

diff --git a/src/compiledlib/cpuFactory b/src/compiledlib/cpuFactory
--- a/src/compiledlib/cpuFactory
+++ b/src/compiledlib/cpuFactory
@@ -1,14 +1,68 @@
-CP='../../build/classes:../../lib/*'
-CP='../../bin:../../lib/*'
+# Sanity checks
 
 # Where things go
-D=..
+OUTDIR=../../src
+
+if test ! -d $OUTDIR/compiledlib/dov
+then
+    echo "The output directory $OUTDIR/compiledlib/dov does not exist"
+    exit 1
+fi
+
+C=../../bin
+L=../../lib
+if test -d $C
+then
+	if test ! -d $L
+	then
+		echo "Found $C but not $L.  This is too confusing."
+		exit 1
+	fi
+else
+	C2=../../build/classes
+	if test -d $C2
+	then
+		if test -d $L
+		then
+			echo "Warning - $C is missing.  Trying $C2" 
+			C="$C2"
+		else
+			echo "Found $C2 but not $L.  This is too confusing."
+			exit 1
+		fi
+	else
+		echo "$C and $C2 both missing.  Giving up"
+		exit 1
+	fi
+fi
+
+F=CpuFactory.class
+X=`find $C -name "$F" -print -quit`
+if test "X$X" = "X"
+then
+    echo "Did not find $F in $C.  This may not work."
+fi
+
+CP="$C:$L/*"
+
 
 # Binary
 B="$1"
 if test "X$B" = "X"
 then
     B=../../SimpleBinaryReader/data/func1
+    if test ! -f $B
+    then
+	echo "$B does not exist. Are you running this in the right place?"
+	B=../SimpleBinaryReader/data/func1
+	if test -f $B
+	then
+	    echo "OK.  Found $B.  You could still be in trouble though."
+	else
+	    echo "Did not find $B either.  Giving up."
+	    exit 1
+	fi
+    fi
 fi
 
 # First, some hacking to build an omnibus CPU
@@ -22,7 +76,7 @@ then
 java -classpath $CP \
 	com/appcomsci.mips.cpu.CpuBuilder \
 	--class=AllCpu \
-	--output.directory=$D
+	--output.directory=$OUTDIR
 
 if test -f AllCpu.cpp
 then
@@ -42,7 +96,7 @@ fi
 java -classpath $CP \
 	com/appcomsci.mips.cpu.CpuBuilder \
 	--class=BigCpu \
-	--output.directory=$D \
+	--output.directory=$OUTDIR \
 	--entry.point=sfe_main \
 	--function.load.list=sfe_main,func_a,func_b $B
 
@@ -50,10 +104,10 @@ java -classpath $CP \
 
 # uncomment to clean up
 # better to use ant to do this: ant cleangenerated
-# rm -rf $D/compiledlib/dov/*.cpp $D/compiledlib/dov/Cpu_*.java $D/compiledlib/dov/CpuImpl_*.java
+# rm -rf $OUTDIR/compiledlib/dov/*.cpp $OUTDIR/compiledlib/dov/Cpu_*.java $OUTDIR/compiledlib/dov/CpuImpl_*.java
 
 java -classpath $CP \
 	com.appcomsci.mips.cpu.CpuFactory \
-	--output.directory=$D \
+	--output.directory=$OUTDIR \
 	--entry.point=sfe_main \
 	--function.load.list=sfe_main,func_a,func_b $B
